syms: data/lang/syms.txt
save_model: true
adaptive_pooling: avgpool-16
fixed_input_height: 128
common:
  model_filename: model_h128
crnn:
  cnn_activation: [LeakyReLU,LeakyReLU,LeakyReLU,LeakyReLU]
  cnn_batchnorm: [true,true,true,true]
  cnn_dilation: [1,1,1,1]
  cnn_dropout: [0,0,0,0]
  cnn_kernel_size: [3,3,3,3]
  cnn_num_features: [12,24,48,48]
  cnn_poolsize: [2,2,0,2]
  cnn_stride: [1,1,1,1]
  rnn_layers: 3
  rnn_units: 256
  use_masks: true
logging:
  filepath: model.log
  overwrite: true
  to_stderr_level: INFO
